[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"
optimizer = true
optimizer_runs = 999999
cache_path = 'cache_foundry'

[fmt]
line_length = 240
tab_width = 2
bracket_spacing = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/config/README.md#all-options